name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # No publicar a pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # State management con GetX
  get: ^4.6.6

  # Formato de fechas e internacionalización
  intl: ^0.19.0

  # Supabase integration (versión estable más reciente a septiembre 2025)
  supabase_flutter: ^2.5.7

  # Variables de entorno (.env)
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
